# Site Info
title: Otto's Dev. Blog.
tagline: '0770 Developer blog'
description: ""
baseurl: ""
url: http://ottoyoon98.github.io/otto
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: otto
  description: A passionate <strong>coding, algorithm, veganism and environment</strong>.
  gravatar: 1a472965526fcb700e603f662a72f96e # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/ottoyoon98
    github:    https://github.com/ottoyoon98
    # facebook:  <hide>
    twitter:   https://twitter.com/ottoyoon98
    #weibo:     http://weibo.com/41173780
    #email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'https://ottoyoon98.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/mountain.jpg
  caption: Original Artwork &copy; <a href="https://pixabay.com/ko/illustrations/%EC%82%B0-%EC%96%B8%EB%8D%95-%EC%88%B2-%EC%95%84%ED%8A%B8-%EB%82%B3-%EB%8B%A4-5309606/">BUMIPUTRA</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
